import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, BarChart3, ChevronRight, CircleGauge, FileText, History, Plus, Radar, Server, Settings, ShieldCheck, Trash2, X, Zap } from 'lucide-react'
import { api } from './api'
import type { DiscoveryProfile, Target, TargetInput } from './types'

const emptyForm:TargetInput={name:'',ip_address:'',port:53,description:'',environment:'Lab',udp_enabled:true,tcp_enabled:true,tags:[]}

export default function App(){
  const queryClient=useQueryClient();const [showForm,setShowForm]=useState(false);const [form,setForm]=useState<TargetInput>(emptyForm);const [notice,setNotice]=useState('');const [profile,setProfile]=useState<{target:Target;data:DiscoveryProfile}|null>(null)
  const targets=useQuery({queryKey:['targets'],queryFn:api.listTargets})
  const create=useMutation({mutationFn:api.createTarget,onSuccess:()=>{queryClient.invalidateQueries({queryKey:['targets']});setForm(emptyForm);setShowForm(false);setNotice('Target güvenli biçimde kaydedildi.')},onError:(e:Error)=>setNotice(e.message)})
  const remove=useMutation({mutationFn:api.deleteTarget,onSuccess:()=>queryClient.invalidateQueries({queryKey:['targets']}),onError:(e:Error)=>setNotice(e.message)})
  const discover=useMutation({mutationFn:async(t:Target)=>({target:t,data:await api.discoverTarget(t.id)}),onSuccess:setProfile,onError:(e:Error)=>setNotice(e.message)})
  const submit=(e:FormEvent)=>{e.preventDefault();setNotice('');create.mutate(form)}
  const items=targets.data??[]
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brandmark"><Radar size={22}/></div><div><b>DNStrike</b><small>RESILIENCE LAB</small></div></div>
      <nav><Nav icon={<CircleGauge/>} label="Dashboard"/><Nav active icon={<Server/>} label="Targets"/><Nav icon={<Zap/>} label="New Test"/><Nav icon={<Activity/>} label="Running Tests" badge="0"/><Nav icon={<History/>} label="Test History"/><Nav icon={<FileText/>} label="Reports"/></nav>
      <div className="sideBottom"><Nav icon={<Settings/>} label="Settings"/><div className="safety"><ShieldCheck size={18}/><div><b>Safe mode active</b><span>Private networks only</span></div></div></div>
    </aside>
    <main><header><div><span className="eyebrow">INFRASTRUCTURE</span><h1>DNS Targets</h1><p>Manage authorized resolvers and inspect their protocol posture.</p></div><button className="primary" onClick={()=>setShowForm(true)}><Plus size={17}/>Add target</button></header>
      {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<X size={15}/></div>}
      <section className="summary"><Stat label="Total targets" value={String(items.length)} detail="Authorized endpoints"/><Stat label="UDP enabled" value={String(items.filter(x=>x.udp_enabled).length)} detail="Datagram checks ready"/><Stat label="TCP enabled" value={String(items.filter(x=>x.tcp_enabled).length)} detail="Fallback checks ready"/></section>
      <section className="panel"><div className="panelTitle"><div><h2>Configured targets</h2><p>Discovery sends one bounded probe per enabled protocol.</p></div><span className="count">{items.length} TARGETS</span></div>
        {targets.isLoading?<div className="empty">Loading targets…</div>:targets.isError?<div className="empty error">Targets could not be loaded.</div>:items.length===0?<div className="empty"><div className="emptyIcon"><Server/></div><h3>No targets yet</h3><p>Add a private or local DNS server to begin discovery.</p><button className="secondary" onClick={()=>setShowForm(true)}>Add your first target</button></div>:<div className="tableWrap"><table><thead><tr><th>Target</th><th>Endpoint</th><th>Environment</th><th>Protocols</th><th>Tags</th><th></th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td><div className="targetName"><span className="statusDot"/><div><b>{t.name}</b><small>{t.description||'No description'}</small></div></div></td><td><code>{t.ip_address}:{t.port}</code></td><td>{t.environment||'—'}</td><td><div className="pills">{t.udp_enabled&&<span>UDP</span>}{t.tcp_enabled&&<span>TCP</span>}</div></td><td><div className="tags">{t.tags.length?t.tags.map(x=><i key={x}>{x}</i>):'—'}</div></td><td><div className="actions"><button title="Discover" disabled={discover.isPending} onClick={()=>discover.mutate(t)}><Radar size={16}/>Discover</button><button className="iconButton danger" title="Delete" onClick={()=>{if(confirm(`${t.name} silinsin mi?`))remove.mutate(t.id)}}><Trash2 size={16}/></button><ChevronRight size={16}/></div></td></tr>)}</tbody></table></div>}
      </section>
    </main>
    {showForm&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setShowForm(false)}}><form className="modal" onSubmit={submit}><div className="modalHead"><div><span className="eyebrow">AUTHORIZED ASSET</span><h2>Add DNS target</h2></div><button type="button" className="iconButton" onClick={()=>setShowForm(false)}><X/></button></div><p className="helper">Only private, loopback, link-local and IPv6 ULA addresses are accepted.</p><div className="grid2"><Field label="Target name"><input required maxLength={100} placeholder="Internal AD DNS" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Environment"><input placeholder="Production Lab" value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}/></Field><Field label="DNS server IP"><input required placeholder="192.168.1.53" value={form.ip_address} onChange={e=>setForm({...form,ip_address:e.target.value})}/></Field><Field label="Port"><input required type="number" min={1} max={65535} value={form.port} onChange={e=>setForm({...form,port:Number(e.target.value)})}/></Field></div><Field label="Description"><textarea rows={3} placeholder="Resolver role and ownership notes" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Tags (comma separated)"><input placeholder="ad, branch-01" onChange={e=>setForm({...form,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></Field><div className="checks"><label><input type="checkbox" checked={form.udp_enabled} onChange={e=>setForm({...form,udp_enabled:e.target.checked})}/>UDP enabled</label><label><input type="checkbox" checked={form.tcp_enabled} onChange={e=>setForm({...form,tcp_enabled:e.target.checked})}/>TCP enabled</label></div>{create.isError&&<div className="formError">{(create.error as Error).message}</div>}<div className="modalFoot"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary" disabled={create.isPending}>{create.isPending?'Saving…':'Save target'}</button></div></form></div>}
    {profile&&<Discovery target={profile.target} data={profile.data} close={()=>setProfile(null)}/>}
  </div>
}

function Nav({icon,label,active,badge}:{icon:React.ReactNode;label:string;active?:boolean;badge?:string}){return <button className={active?'nav active':'nav'}>{icon}<span>{label}</span>{badge&&<i>{badge}</i>}</button>}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Bool({label,value}:{label:string;value:boolean}){return <div className="checkRow"><span>{label}</span><b className={value?'yes':'no'}>{value?'Supported':'Not detected'}</b></div>}
function Discovery({target,data,close}:{target:Target;data:DiscoveryProfile;close:()=>void}){return <div className="overlay"><div className="modal discovery"><div className="modalHead"><div><span className="eyebrow">SERVER PROFILE</span><h2>{target.name}</h2><code>{data.target}</code></div><button className="iconButton" onClick={close}><X/></button></div><div className="latency"><div><span>Average latency</span><strong>{data.average_latency_ms.toFixed(2)} ms</strong></div><BarChart3/></div><div className="protocols"><Protocol name="UDP" item={data.udp}/><Protocol name="TCP" item={data.tcp}/></div><div className="checksGrid"><Bool label="Recursion" value={data.recursion_enabled}/><Bool label="Authoritative" value={data.authoritative}/><Bool label="EDNS" value={data.edns_supported}/><Bool label="DNSSEC signals" value={data.dnssec_supported}/><Bool label="TCP fallback" value={data.tcp_fallback}/><div className="checkRow"><span>Response size</span><b>{data.response_size} B</b></div></div><div className="flags">FLAGS <b>RA {Number(data.flags.ra)}</b><b>RD {Number(data.flags.rd)}</b><b>AA {Number(data.flags.aa)}</b><b>TC {Number(data.flags.tc)}</b></div><div className="modalFoot"><button className="primary" onClick={close}>Done</button></div></div></div>}
function Protocol({name,item}:{name:string;item:DiscoveryProfile['udp']}){return <div className={item.available?'protocol ok':'protocol fail'}><span>{name}</span><strong>{item.available?'Available':'Unavailable'}</strong><small>{item.available?`${item.latency_ms.toFixed(2)} ms`:item.error}</small></div>}
